apiVersion: entity.humanitec.io/v1
kind: Definition
metadata:
  id: custom-azure-redis-cache
entity:
  type: redis
  name: custom-azure-redis-cache
  driver_type: humanitec/terraform
  driver_inputs:
    values:
      source: 
        url: "https://github.com/ErikBaer/humanitec-eval-redis.git"
        rev: "refs/heads/main"
      variables: 
        resource_group_name: "ref-arch"
        location: "ger-west-central"
        environment: "${context.env.id}"
        app_name: "${context.app.id}"
        resource_name: "${context.res.id}"
      outputs:
        - name: hostname
          value: "${output.hostname}"
        - name: access_key
          value: "${output.primary_access_key}"
      