apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: custom-azure-redis-cache
entity:
  type: redis
  name: custom-azure-redis-cache
  driver_type: humanitec/terraform
  driver_inputs:
    values:
      source: 
        url: https://github.com/ErikBaer/humanitec-eval.git/tf-resources/azure-redis-cache
        rev: refs/heads/main
      variables: 
        resource_group_name: 
        location: 
        environment: ${context.env.id}
        app_name: ${context.app.id}
        resource_name: ${context.res.id}
      outputs:
        - name: hostname
          value: ${output.redis_cache_hostname}
        - name: access_key
          value: ${output.redis_cache_access_key}
  criteria:
  - env_type: production
